name: algorithmic
version: 0.0.11
homepage: https://github.com/dipu-bd/algorithmic
description: A collection of useful algorithms keeping performance and flexibility on mind.

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
  benchmark: ^0.3.0
  collection: ^1.15.0
  trotter: ^2.0.0-dev.1
  edit_distance: ^0.5.0-nullsafety.0
