name: algorithmic
version: 0.0.5
homepage: https://github.com/dipu-bd/algorithmic
description: A collection of useful algorithms in Dart with keeping performance and flexibility on mind.

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  benchmark: ^0.3.0
  collection: ^1.15.0
